- name:        "hejsa"
  description: "Some long text"
  command:
    cmd: "cargo"
    args: "check"
    directory: "./"
  glob_pattern: ["**/*.rs", "*.toml", "*.yml"]

- name:        "foo"
  command:
    cmd: "./do-something.sh"
  glob_pattern: ["**/*.rs"]

