- name:        "check"
  description: "Some long text"
  command:
    cmd: "cargo"
    args: "check"
    directory: "./"
  glob_pattern: ["**/*.rs", "*.toml", "*.yml"]

- name:        "clippy"
  command:
    cmd: "cargo"
    args: "clippy --all-targets --all-features -- -Dwarnings"
  glob_pattern: ["**/*.rs"]

