
- name:        "hejsa"
  description: "Some long text"
  command:
    cmd: "ls"
    args: "-al"
    directory: "../"
  glob_pattern: ["**.py", "*.json"]

- name:        "foo"
  command:
    cmd: "./do-something.sh"
  glob_pattern: ["**.rs"]

